DEFINE VARIABLE a AS DECIMAL FORMAT ">>,9" NO-UNDO.
DEFINE VARIABLE b AS DECIMAL FORMAT ">>,9" NO-UNDO.
DEFINE VARIABLE c AS DECIMAL FORMAT ">>,9" NO-UNDO.



UPDATE a COLUMN-LABEL "digite um numero" FORMAT ">>,9".
UPDATE b COLUMN-LABEL "digite o segundo numero" FORMAT ">>,9".

c = (a + b) / 2.

DISPLAY "MEDIA = "c FORMAT ">>,9".