DEFINE VARIABLE a AS DECIMAL FORMAT ">>,9" NO-UNDO.
DEFINE VARIABLE b AS DECIMAL FORMAT ">>,9" NO-UNDO.
DEFINE VARIABLE c AS DECIMAL FORMAT ">>,9" NO-UNDO.

UPDATE a COLUMN-LABEL "numero 1" FORMAT ">>,9"
       b COLUMN-LABEL "numero 2" FORMAT ">>,9"
       c COLUMN-LABEL "numero 3" FORMAT ">>,9".


DISPLAY "MEDIA = "((a * 2) + (b * 3) + (c * 5)) / 10 FORMAT ">>,9".