DEFINE VARIABLE a AS DECIMAL FORMAT ">>,9" NO-UNDO.
DEFINE VARIABLE b AS DECIMAL FORMAT ">>,9" NO-UNDO.
DEFINE VARIABLE c AS DECIMAL FORMAT ">>,9" NO-UNDO.
DEFINE VARIABLE d AS DECIMAL FORMAT ">>,9" NO-UNDO.


UPDATE a COLUMN-LABEL "numero 1" FORMAT ">>,9".
UPDATE b COLUMN-LABEL "numero 2" FORMAT ">>,9".
UPDATE c COLUMN-LABEL "numero 3" FORMAT ">>,9".


d = ((a * 2) + (b * 3) + (c * 5)) / 10.

DISPLAY "MEDIA = "d FORMAT ">>,9".