DEFINE VARIABLE a AS INTEGER NO-UNDO.
DEFINE VARIABLE b AS INTEGER NO-UNDO.
DEFINE VARIABLE c AS INTEGER NO-UNDO.
DEFINE VARIABLE d AS INTEGER NO-UNDO.

UPDATE a COLUMN-LABEL "numero 1"
       b COLUMN-LABEL "numero 2"
       c COLUMN-LABEL "numero 3"
       d COLUMN-LABEL "numero 4".

DISPLAY "DIFERENCA = " (a * b) - (c * d).