DEFINE VARIABLE a AS INTEGER NO-UNDO.
DEFINE VARIABLE b AS INTEGER NO-UNDO.
DEFINE VARIABLE c AS INTEGER NO-UNDO.
DEFINE VARIABLE d AS INTEGER NO-UNDO.
DEFINE VARIABLE e AS INTEGER NO-UNDO.


UPDATE a COLUMN-LABEL "numero 1".
UPDATE b COLUMN-LABEL "numero 2".
UPDATE c COLUMN-LABEL "numero 3".
UPDATE d COLUMN-LABEL "numero 4".


e = (a * b) - (c * d).

DISPLAY "DIFERENCA = " e.
